version: '3'
services:
  libre-postgres:
    build:
      context: ./db
    restart: always
    container_name: postgresql
    image: postgresql:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zc504879189..
      POSTGRES_DB: libre_spider
    volumes:
      - ~/docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "2345:5432"
    networks:
      - libre_default

  libre-redis:
    image: redis:7.0.0
    ports:
      - "9736:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ~/docker/redis/conf:/usr/local/etc/redis/redis.conf  # 挂载自定义配置文件
      - ~/docker/redis/data:/data  # 挂载数据目录
    restart: always
    container_name: libre-redis
    hostname: libre-redis
    networks:
      - libre_default
  libre-video:
    build:
      context: ./app
    volumes:
      - ~/docker/video:/app/video
    restart: always
    ports:
      - "9000:9000"
    container_name: video
    hostname: libre-video
    image: video
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    networks:
      - libre_default

networks:
  libre_default:
    driver: bridge

#  libre-es:
#    image: elasticsearch:8.7.0
#    ports:
#      - "9200:9200"
#    restart: always
#    container_name: libre-es
#    hostname: pig-es
#    networks:
#      - libre_default
