server:
  port: 9870

spring:
  application:
    name: video-spider
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  codec:
    max-in-memory-size: 100MB
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

logging:
  level:
    org.elasticsearch.client: error

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.13:5432/libre_video
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 1000000
      maximum-pool-size: 5
      max-lifetime: 1800000
      minimum-idle: 1
  elasticsearch:
    uris: http://127.0.0.1:9200
    connection-timeout: 10s
libre:
  oss:
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: video
    endpoint: http://127.0.0.1:9000

video:
  download-path: /Users/libre/video/
  ffmpeg-path: /usr/local/Cellar/ffmpeg/5.0.1/bin/
  mp4box-path: MP4Box/

---
spring:
  config:
    activate:
      on-profile: prod
    location: ../config/application.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://127.0.0.1:6033/libre?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useCursorFetch=true
    username: root
    password: ENC(pS3X2GTc99Gw5vhMMZWmHzdvtRRHO1o3)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 200
      connection-test-query: select 1

  elasticsearch:
    uris: http://172.17.0.3:9200
    username: elastic
    password: ENC(hoWyhk+6Fzt7jqzr0DmeH3SP3Y/5hEMK)
  data:
    redis:
      password: password
      host: 127.0.0.1

video:
  download-path: /libre/video/
  ffmpeg-path: /usr/bin/
  mp4box-path: /libre/gpac/gpac_public/bin/gcc/MP4Box/
