server:
  port: 9870

spring:
  application:
    name: video-spider
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  codec:
    max-in-memory-size: 100MB
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

logging:
  level:
    org.elasticsearch.client: error

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/libre_video
    username: libre
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 1000000
      maximum-pool-size: 5
      max-lifetime: 1800000
      minimum-idle: 1
  elasticsearch:
    uris: http://127.0.0.1:9200
  threads:
    virtual:
      enabled: true

video:
  download-path: /Users/libre/video/
  ffmpeg-path: /usr/local/Cellar/ffmpeg/5.0.1/bin/
  mp4box-path: MP4Box/

---
spring:
  config:
    activate:
      on-profile: prod
    location: ../config/application.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://libre-postgres:2543/libre_video
    username: postgres
    password: zc504879189..
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 1000000
      maximum-pool-size: 5
      max-lifetime: 1800000
      minimum-idle: 1
  elasticsearch:
    username: elastic
    password: zc504879189~~
    uris: http://13.230.110.72:9201
  data:
    redis:
      password: zc504879189..
      host: libre-redis
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

video:
  download-path: /app/video/
  ffmpeg-path: /usr/bin/
  mp4box-path: /libre/gpac/gpac_public/bin/gcc/MP4Box/
